[toolchain]
anchor_version = "0.31.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
lien_hook_executor = "LienH00kExecutor1111111111111111111111111111"

[programs.mainnet]
lien_hook_executor = "LienH00kExecutor1111111111111111111111111111"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"
