[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
lien_hook_executor = "5yNMqcyZsGQJk4xvw4jjvoRBSnGs8mgramEa3HQe5faD"

[programs.mainnet]
lien_hook_executor = "5yNMqcyZsGQJk4xvw4jjvoRBSnGs8mgramEa3HQe5faD"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"
